name: Java CI

on:
  pull_request:
    branches:
      - Feature/wrims-devops
  push:
    branches:
      - Feature/wrims-devops
      - Feature/wrims-installer-devops

permissions: read-all

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Build with Gradle
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ./gradlew clean
        ./gradlew :wrims-core:build
        ./gradlew build
        ./gradlew :wrims-gui:zipWrimsGui

    - name: Upload Core jar
      uses: actions/upload-artifact@v4.0.0
      with:
        name: wrims-core
        path: |
          ./wrims-core/build/libs/*.jar

    - name: Upload Wrims-IDE jar
      uses: actions/upload-artifact@v4.0.0
      with:
        name: wrims-ide
        path: |
          ./wrims-ide/build/libs/*.jar

    - name: Upload third-party jar
      uses: actions/upload-artifact@v4.0.0
      with:
        name: third-party
        path: |
          ./third-party/build/libs/*.jar

    - name: Upload dwr-hecdssvue jar
      uses: actions/upload-artifact@v4.0.0
      with:
        name: dwr-hecdssvue
        path: |
          ./hecdssvue/build/libs/*.jar

    - name: Upload jdiagram jar
      uses: actions/upload-artifact@v4.0.0
      with:
        name: jdiagram
        path: |
          ./jdiagram/build/libs/*.jar

    - name: Upload xtext-editor jar
      uses: actions/upload-artifact@v4.0.0
      with:
        name: xtext-editor
        path: |
          ./xtext-editor/build/libs/*.jar

    - name: Upload xtext-editor-ui jar
      uses: actions/upload-artifact@v4.0.0
      with:
        name: xtext-editor-ui
        path: |
          ./xtext-editor-ui/build/libs/*.jar

    - name: Upload WRIMS GUI zip
      uses: actions/upload-artifact@v4.0.0
      with:
        name: wrims-gui-installer
        path: |
          ./wrims-gui/build/installer/*.zip