# This is a manually triggered wrims compute

name: WRIMS compute
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "wrims_compute"
  wrims_compute:
    # Verify the WRIMS compute on a Windows 2022 runner
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      # to publish the report to GitHub Packages, run the publish task in place of "testReport"
      - name: Run a WRIMS compute and generate a comparison report
        run: ./gradlew --no-daemon :wrims-comparison-test:testReport
        env:
          PKG_USERNAME: ${{ github.actor }}
          PKG_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save the comparison report as an artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: reports
          path: ./wrims-comparison-test/build/testProjects/*.pdf